staples:
  - salt
  - black pepper
  - olive oil
  - vegetable oil
  - cooking spray
  - garlic
  - all-purpose flour
  - sugar
  - brown sugar
  - baking powder
  - baking soda
  - vanilla extract
  - soy sauce
  - apple cider vinegar
  - red wine vinegar
  - white vinegar
  - dried oregano
  - dried basil
  - cumin
  - paprika
  - chili powder
  - garlic powder
  - onion powder
  - crushed red pepper
  - bay leaves
  - cinnamon
  - Italian seasoning
  - cayenne
  - cornstarch
